# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

services:
  - docker

apt_packages:
  - libudunits2-dev

before_install:
  - export CURWD=`pwd`
  - sudo apt-get install -y libxml2
  - sudo apt-get install libproj-dev libgeos++-dev
  - cd
  - wget http://download.osgeo.org/gdal/2.1.0/gdal-2.1.0.tar.gz
  - tar zxf gdal-2.1.0.tar.gz
  - cd gdal-2.1.0
  - ./configure
  - make
  - sudo make install
  - cd
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz
  - tar zxvf proj-4.9.3.tar.gz
  - cd proj-4.9.3
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - sudo apt-get install texlive-latex-recommended
  - cd $CURWD
  - docker run --name geonetwork -d -p 8080:8080 pobsteta/docker-geonetwork:3.0.5

r:
  - release
  - devel
  
r_github_packages:
  - eblondel/geometa

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - testthat
  - covr

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change