# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: required
cache: packages

os:
  - linux

apt_packages:
  - libxml2-dev

services:
  - docker

before_install:
  # mainly for installing sf (which requires units/rgeos/rgdal)
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'
  - docker run --name geonetwork -d -p 8080:8080 pobsteta/docker-geonetwork:3.0.5

r:
  #- release
  - devel
  
r_github_packages:
  - hadley/devtools
  - eblondel/geometa

r_packages:
  - R6
  - openssl
  - httr
  - XML
  - sf
  - testthat
  - covr

r_check_args: --as-cran

after_script:
 - ./travis-tool.sh dump_logs
 
after_success:
 - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    on_success: change
    on_failure: change